PROJECT_NAME = N64FlashcartMenu

.DEFAULT_GOAL := all

SOURCE_DIR = src
ASSETS_DIR = assets
FILESYSTEM_DIR = filesystem
BUILD_DIR = build
OUTPUT_DIR = output

MENU_VERSION ?= "Preview release"
BUILD_TIMESTAMP = "$(shell TZ='UTC' date "+%Y-%m-%d %H:%M:%S %:z")"

include $(N64_INST)/include/n64.mk

N64_ROM_SAVETYPE = none
N64_ROM_RTC = 1
N64_ROM_REGIONFREE = 1
N64_ROM_REGION = E

N64_CFLAGS += -iquote $(SOURCE_DIR) -iquote $(ASSETS_DIR) -I $(SOURCE_DIR)/libs -isystem $(SOURCE_DIR)/libs/miniz -flto=auto $(FLAGS)

SRCS = \
	main.c \
	boot/boot.c \
	boot/cheats.c \
	boot/cic.c \
	boot/reboot.S \
	flashcart/flashcart_utils.c \
	flashcart/flashcart.c \
	flashcart/sc64/sc64_ll.c \
	flashcart/sc64/sc64.c \
	libs/libspng/spng/spng.c \
	libs/miniz/miniz_tdef.c \
	libs/miniz/miniz_tinfl.c \
	libs/miniz/miniz_zip.c \
	libs/miniz/miniz.c \
	menu/ini_parser.c \
	menu/actions.c \
	menu/bookkeeping.c \
	menu/cart_load.c \
	menu/datel_codes.c \
	menu/fonts.c \
	menu/hidden.c \
	menu/labels.c \
	menu/hdmi.c \
	menu/menu.c \
	menu/path.c \
	menu/png_decoder.c \
	menu/rom_info.c \
	menu/settings.c \
	menu/sound.c \
	menu/ui_components/background.c \
	menu/ui_components/boxart.c \
	menu/ui_components/carousel.c \
	menu/ui_components/carousel_scroll.c \
	menu/ui_components/loading_animation.c \
	menu/ui_components/palette.c \
	menu/ui_components/common.c \
	menu/ui_components/context_menu.c \
	menu/ui_components/file_info.c \
	menu/ui_components/file_list.c \
	menu/ui_components/game_info.c \
	menu/ui_components/icons.c \
	menu/ui_components/keyboard.c \
	menu/ui_components/option_list.c \
	menu/ui_components/tab_header.c \
	menu/ui_components/tabs.c \
	menu/usb_comm.c \
	menu/views/browser.c \
	menu/views/credits.c \
	menu/views/datel_code_editor.c \
	menu/views/error.c \
	menu/views/fault.c \
	menu/views/file_info.c \
	menu/views/history_favorites.c \
	menu/views/image_viewer.c \
	menu/views/text_viewer.c \
	menu/views/load_rom.c \
	menu/views/startup.c \
	menu/views/system_info.c \
	menu/views/settings_editor.c \
	menu/views/settings_hub.c \
	menu/views/rtc.c \
	menu/views/flashcart_info.c \
	menu/views/cpakfs_manager.c \
	menu/views/cpak_dump_info.c \
	menu/views/cpak_note_dump_info.c \
	utils/cpakfs_utils.c \
	utils/fs.c \
	utils/utf_converter.c \

# Analogue OS is drawn on a 20-unit pixel grid: 20px renders 1:1, 40px renders 2:1.
# 12px (captions, info rows) is off-grid, so it is anti-aliased instead of monochrome, with 1px
# extra letter spacing for readability.
FONT_SIZES = 12 20 40
FONT_TTF = $(ASSETS_DIR)/fonts/AnalogueOS-Regular.ttf

SOUNDS_WAV = \
	cursorsound.wav \
	back.wav \
	enter.wav \
	error.wav \
	settings.wav

SOUNDS_XM ?=

IMAGES = \
	cartridge.png \
	cartridge_large.png \
	cartridge_large_outline.png \
	cartridge_large_outline_favorite.png \
	cartridge_large_outline_hidden.png \
	button_a.png \
	button_b.png \
	button_c_right.png \
	button_c_up.png \
	button_c_down.png \
	button_c_left.png \
	button_z.png \
	tab_l.png \
	tab_r.png

# Boot animation frames: generated by scripts/make_boot_animation.py from boot_animation/.
BOOT_IMAGES = $(wildcard $(ASSETS_DIR)/boot/*.png)

OBJS = $(addprefix $(BUILD_DIR)/, $(addsuffix .o,$(basename $(SRCS))))
MINIZ_OBJS = $(filter $(BUILD_DIR)/libs/miniz/%.o,$(OBJS))
SPNG_OBJS = $(filter $(BUILD_DIR)/libs/libspng/%.o,$(OBJS))
DEPS = $(OBJS:.o=.d)

FILESYSTEM = \
	$(foreach s,$(FONT_SIZES),$(FILESYSTEM_DIR)/AnalogueOS-$(s).font64) \
	$(addprefix $(FILESYSTEM_DIR)/, $(notdir $(SOUNDS_WAV:%.wav=%.wav64))) \
	$(addprefix $(FILESYSTEM_DIR)/, $(notdir $(SOUNDS_XM:%.xm=%.xm64))) \
	$(addprefix $(FILESYSTEM_DIR)/, $(notdir $(IMAGES:%.png=%.sprite))) \
	$(addprefix $(FILESYSTEM_DIR)/boot/, $(notdir $(BOOT_IMAGES:%.png=%.sprite))) \
	$(FILESYSTEM_DIR)/boot/eclipse_boot_hall.wav64 \
	$(FILESYSTEM_DIR)/loading_wind.wav

# DEV_SD=1 packs devsd/ (see scripts/make_devsd.py) into rom:/ so emulators have games to show.
# Copied as a whole folder because ROM file names contain spaces, which make can't track.
ifdef DEV_SD
FILESYSTEM += devsd-sync
devsd-sync:
	@echo "    [DEVSD] devsd/ -> $(FILESYSTEM_DIR)/"
	@cp -R devsd/. $(FILESYSTEM_DIR)/
.PHONY: devsd-sync
else
$(shell rm -rf $(FILESYSTEM_DIR)/N64 $(FILESYSTEM_DIR)/menu)
endif

$(MINIZ_OBJS): N64_CFLAGS+=-Wno-unused-function -fcompare-debug-second
$(SPNG_OBJS): N64_CFLAGS+=-DSPNG_USE_MINIZ -fcompare-debug-second
$(FILESYSTEM_DIR)/%.wav64: AUDIOCONV_FLAGS=--wav-compress 1
$(FILESYSTEM_DIR)/%.sprite: MKSPRITE_FLAGS=--format RGBA16 --compress 1

$(@info $(shell mkdir -p ./$(FILESYSTEM_DIR) &> /dev/null))

$(FILESYSTEM_DIR)/AnalogueOS-%.font64: FONT_FLAGS=--monochrome
$(FILESYSTEM_DIR)/AnalogueOS-12.font64: FONT_FLAGS=--char-spacing 1
$(FILESYSTEM_DIR)/AnalogueOS-%.font64: $(FONT_TTF)
	@echo "    [FONT] $@"
	@mkdir -p $(BUILD_DIR)/fonts/$*
	@$(N64_MKFONT) --compress 1 $(FONT_FLAGS) --size $* --ellipsis 2E,3 -o $(BUILD_DIR)/fonts/$* "$<"
	@mv $(BUILD_DIR)/fonts/$*/AnalogueOS-Regular.font64 $@

$(FILESYSTEM_DIR)/%.wav64: $(ASSETS_DIR)/sounds/%.wav
	@echo "    [AUDIO WAV] $@"
	@$(N64_AUDIOCONV) $(AUDIOCONV_FLAGS) -o $(FILESYSTEM_DIR) "$<"

$(FILESYSTEM_DIR)/%.xm64: $(ASSETS_DIR)/sounds/%.xm
	@echo "    [AUDIO XM] $@"
	@$(N64_AUDIOCONV) $(AUDIOCONV_FLAGS) -o $(FILESYSTEM_DIR) "$<"

$(FILESYSTEM_DIR)/%.sprite: $(ASSETS_DIR)/images/%.png
	@echo "    [SPRITE] $@"
	@$(N64_MKSPRITE) $(MKSPRITE_FLAGS) -o $(dir $@) "$<"

# Played from memory after a game loads (rom:/ is overwritten by then), so kept as plain WAV.
$(FILESYSTEM_DIR)/loading_wind.wav: $(ASSETS_DIR)/sounds/loading_wind_1s.wav
	@echo "    [AUDIO RAW] $@"
	@cp "$<" $@

$(FILESYSTEM_DIR)/boot/eclipse_boot_hall.wav64: boot_animation/boot_audio/eclipse_boot_hall.wav
	@echo "    [AUDIO WAV] $@"
	@mkdir -p $(dir $@)
	@$(N64_AUDIOCONV) --wav-compress 1 -o $(dir $@) "$<"

$(FILESYSTEM_DIR)/boot/%.sprite: $(ASSETS_DIR)/boot/%.png
	@echo "    [SPRITE] $@"
	@mkdir -p $(dir $@)
	@$(N64_MKSPRITE) --format CI8 --compress 1 -o $(dir $@) "$<"

$(BUILD_DIR)/$(PROJECT_NAME).dfs: $(FILESYSTEM)

$(BUILD_DIR)/menu/views/credits.o: .FORCE
$(BUILD_DIR)/menu/views/credits.o: FLAGS+=-DMENU_VERSION=\"$(MENU_VERSION)\" -DBUILD_TIMESTAMP=\"$(BUILD_TIMESTAMP)\"

$(BUILD_DIR)/$(PROJECT_NAME).elf: $(OBJS)

disassembly: $(BUILD_DIR)/$(PROJECT_NAME).elf
	@$(N64_OBJDUMP) -S $< > $(BUILD_DIR)/$(PROJECT_NAME).lst
.PHONY: disassembly

$(PROJECT_NAME).z64: N64_ROM_TITLE=$(PROJECT_NAME)
$(PROJECT_NAME).z64: $(BUILD_DIR)/$(PROJECT_NAME).dfs

$(@info $(shell mkdir -p ./$(OUTPUT_DIR) &> /dev/null))

$(OUTPUT_DIR)/$(PROJECT_NAME).n64: $(PROJECT_NAME).z64
	@mv $< $@

sc64: $(OUTPUT_DIR)/$(PROJECT_NAME).n64
	@cp $< $(OUTPUT_DIR)/sc64menu.n64
.PHONY: sc64

all: $(OUTPUT_DIR)/$(PROJECT_NAME).n64 sc64
.PHONY: all

clean:
	@rm -f ./$(FILESYSTEM)
	@find ./$(FILESYSTEM_DIR) -type d -empty -delete
	@rm -rf ./$(BUILD_DIR) ./$(OUTPUT_DIR)
.PHONY: clean

format:
	@find ./$(SOURCE_DIR) \
		-path \./$(SOURCE_DIR)/libs -prune \
		-o -iname *.c -print \
		-o -iname *.h -print \
		| xargs clang-format -i

run: $(OUTPUT_DIR)/$(PROJECT_NAME).n64
ifeq ($(OS),Windows_NT)
	./localdeploy.bat
else
	./remotedeploy.sh
endif
.PHONY: run

run-debug: $(OUTPUT_DIR)/$(PROJECT_NAME).n64
ifeq ($(OS),Windows_NT)
	./localdeploy.bat /d
else
	./remotedeploy.sh -d
endif
.PHONY: run-debug

run-debug-reboot: $(OUTPUT_DIR)/$(PROJECT_NAME).n64
ifeq ($(OS),Windows_NT)
	./localdeploy.bat /dr
else
	./remotedeploy.sh -dr
endif
.PHONY: run-debug-reboot

run-debug-upload: $(OUTPUT_DIR)/$(PROJECT_NAME).n64
ifeq ($(OS),Windows_NT)
	./localdeploy.bat /dur
else
	./remotedeploy.sh -dur
endif
.PHONY: run-debug-upload

# test:
#   TODO: run tests

.FORCE:

-include $(DEPS)
