// Generated by scripts/make_n64_logo.py from assets/images/n64logo_anim.gif - do not edit.

#ifndef N64_LOGO_FRAMES_H__
#define N64_LOGO_FRAMES_H__

#define N64_LOGO_FRAMES     (56)
#define N64_LOGO_WIDTH      (160)    // padded; the logo is centred in it
#define N64_LOGO_HEIGHT     (168)
#define N64_LOGO_FRAME_MS   (107)     // one turn in 6s

#endif
