// Generated by scripts/make_n64_logo.py from assets/images/per2_n64/ - do not edit.

#ifndef N64_LOGO_FRAMES_H__
#define N64_LOGO_FRAMES_H__

#define N64_LOGO_FRAMES     (119)
#define N64_LOGO_WIDTH      (176)    // padded; the logo is centred in it
#define N64_LOGO_HEIGHT     (168)
#define N64_LOGO_LOOP_MS    (3967)   // half a turn, frames evenly spaced in it

#endif
