// Generated by scripts/make_n64_logo.py from assets/images/n64logo_anim.gif - do not edit.

#ifndef N64_LOGO_FRAMES_H__
#define N64_LOGO_FRAMES_H__

#define N64_LOGO_FRAMES     (240)
#define N64_LOGO_WIDTH      (160)    // padded; the logo is centred in it
#define N64_LOGO_HEIGHT     (168)
#define N64_LOGO_LOOP_MS    (8000)   // one turn, frames evenly spaced in it

#endif
