#!/usr/bin/env python3
"""Turn the spinning N64 logo render into frames for the screenshot placeholder.

The Library shows it in the screenshot area whenever no screenshot is showing (the gallery is
off or the game has none). Reads assets/images/<render>/NNNN.png, a Blender render of half a
turn at FPS (the logo looks the same after half a turn, and the last frame is dropped so it loops
seamlessly), and writes

  assets/n64logo/NNN.png         each frame cropped to the logo's extent over the whole turn,
                                 scaled to HEIGHT px tall and padded to an 8-pixel multiple width,
                                 with hard-edged transparency (the menu blits in copy mode) and
                                 one palette shared by every frame, transparent first (CI8)
  src/menu/n64_logo_frames.h     frame count, size and loop time, and each frame's opaque extent
                                 (the screensaver bounces the logo off its visible edges)

Usage: scripts/make_n64_logo.py [render=per2_n64]   (a folder in assets/images/, e.g. per1_n64)
"""

import glob
import os
import sys

from PIL import Image

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..')
RENDERS = os.path.join(ROOT, 'assets', 'images')
DEFAULT_RENDER = 'per2_n64'
OUT_IMAGES = os.path.join(ROOT, 'assets', 'n64logo')
OUT_HEADER = os.path.join(ROOT, 'src', 'menu', 'n64_logo_frames.h')

HEIGHT = 168            # GAME_INFO_SCREENSHOT_HEIGHT: the logo fills the screenshot area's height
FPS = 30                # the render's frame rate (and the menu's)
COLOURS = 255           # palette entries after the transparent one


def main():
    render = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_RENDER
    source_dir = os.path.join(RENDERS, render)
    paths = sorted(glob.glob(os.path.join(source_dir, '*.png')))
    if not paths:
        raise SystemExit(f'No frames in {source_dir}')
    source = [Image.open(p).convert('RGBA') for p in paths]

    # Crop every frame to the logo's extent over the whole turn, so it stays put, then scale.
    boxes = [f.getbbox() for f in source]
    box = (min(b[0] for b in boxes), min(b[1] for b in boxes),
           max(b[2] for b in boxes), max(b[3] for b in boxes))
    width = round((box[2] - box[0]) * HEIGHT / (box[3] - box[1]))
    padded_width = (width + 7) // 8 * 8
    frames = []
    for f in source:
        # Scale premultiplied so the transparent background doesn't darken the edges.
        scaled = f.crop(box).convert('RGBa').resize((width, HEIGHT), Image.Resampling.LANCZOS).convert('RGBA')
        canvas = Image.new('RGBA', (padded_width, HEIGHT), (0, 0, 0, 0))
        canvas.paste(scaled, ((padded_width - width) // 2, 0))
        frames.append(canvas)

    # One palette for all frames, from their opaque pixels.
    opaque = [p[:3] for f in frames for p in f.getdata() if p[3] >= 128]
    sample = Image.new('RGB', (len(opaque), 1))
    sample.putdata(opaque)
    palette_image = sample.quantize(COLOURS, method=Image.Quantize.MEDIANCUT)
    palette = palette_image.getpalette()[:COLOURS * 3]

    os.makedirs(OUT_IMAGES, exist_ok=True)
    for old in glob.glob(os.path.join(OUT_IMAGES, '*.png')):
        os.remove(old)
    extents = []
    for n, f in enumerate(frames):
        indexed = f.convert('RGB').quantize(palette=palette_image, dither=Image.Dither.NONE)
        alpha = f.getchannel('A').tobytes()
        pixels = bytes(i + 1 if a >= 128 else 0 for i, a in zip(indexed.tobytes(), alpha))
        out = Image.frombytes('P', f.size, pixels)
        out.putpalette([0, 0, 0] + palette)
        out.save(os.path.join(OUT_IMAGES, f'{n:03d}.png'), transparency=0)
        extents.append(out.point(lambda i: 255 if i else 0).getbbox())

    loop_ms = round(len(frames) * 1000 / FPS)
    header = [
        f'// Generated by scripts/make_n64_logo.py from assets/images/{render}/ - do not edit.',
        '',
        '#ifndef N64_LOGO_FRAMES_H__',
        '#define N64_LOGO_FRAMES_H__',
        '',
        '#include <stdint.h>',
        '',
        f'#define N64_LOGO_FRAMES     ({len(frames)})',
        f'#define N64_LOGO_WIDTH      ({padded_width})    // padded; the logo is centred in it',
        f'#define N64_LOGO_HEIGHT     ({HEIGHT})',
        f'#define N64_LOGO_LOOP_MS    ({loop_ms})   // half a turn, frames evenly spaced in it',
        '',
        '/** @brief Per frame, the box the logo covers in it: left, top, right, bottom (exclusive). */',
        'static const struct { uint8_t x0, y0, x1, y1; } n64_logo_extents[N64_LOGO_FRAMES] = {',
    ]
    header += [f'    {{ {x0}, {y0}, {x1}, {y1} }},' for x0, y0, x1, y1 in extents]
    header += [
        '};',
        '',
        '#endif',
        '',
    ]
    with open(OUT_HEADER, 'w', newline='\n') as f:
        f.write('\n'.join(header))
    print(f'{render}: {len(frames)} frames, {padded_width}x{HEIGHT}, loop {loop_ms}ms')


if __name__ == '__main__':
    main()
