#!/usr/bin/env python3
"""Turn the boot animation frames into cropped, paletted images for the menu.

Reads boot_animation/eclipse_intro/intro_NNNN.png (640x480, see boot_animation/README.txt)
and writes

  assets/boot/NN.png                 one image per distinct frame, cropped to what differs from
                                     the background and stored with an exact palette, background
                                     first and transparent (CI8 sprites)
  src/menu/boot_animation_frames.h   the background colour, and per frame which image to draw
                                     and where

The background is the colour of frame 1, which must be uniform (#231A2E for the Eclipse intro);
the menu fills the screen with it. Blank (background-only) frames get no image; identical frames
share one.

Usage: scripts/make_boot_animation.py [frames_dir=boot_animation/eclipse_intro]
"""

import glob
import os
import sys

from PIL import Image, ImageChops

OUT_IMAGES = 'assets/boot'
OUT_HEADER = 'src/menu/boot_animation_frames.h'
FPS = 30


def paletted(image, background):
    """Convert an RGB image with <= 256 colours to 'P' mode without changing any pixel."""
    colours = image.getcolors(256)
    if colours is None:
        sys.exit('A frame has more than 256 colours')
    # Background first, so padding and index 0 are the background.
    palette = sorted((c for _, c in colours), key=lambda c: c != background)
    index = {c: i for i, c in enumerate(palette)}
    rgb = image.tobytes()
    pixels = bytes(index[tuple(rgb[i:i + 3])] for i in range(0, len(rgb), 3))
    out = Image.frombytes('P', image.size, pixels)
    out.putpalette([v for c in palette for v in c])
    if palette[0] == background:
        out.info['transparency'] = 0
    return out


def main():
    frames_dir = sys.argv[1] if len(sys.argv) > 1 else 'boot_animation/eclipse_intro'
    paths = sorted(glob.glob(os.path.join(frames_dir, 'intro_*.png')))
    if not paths:
        sys.exit(f'No frames in {frames_dir}')

    os.makedirs(OUT_IMAGES, exist_ok=True)
    for old in glob.glob(os.path.join(OUT_IMAGES, '*.png')):
        os.remove(old)

    images = {}         # (x, y, crop bytes) -> image number
    table = []          # per frame: (image number or -1, x, y)
    total_bytes = 0
    first = Image.open(paths[0]).convert('RGB')
    background = first.getpixel((0, 0))
    if first.getcolors(1) is None:
        sys.exit('Frame 1 must be a uniform background colour')
    for path in paths:
        frame = Image.open(path).convert('RGB')
        bbox = ImageChops.difference(frame, Image.new('RGB', frame.size, background)).getbbox()
        if bbox is None:
            table.append((-1, 0, 0))
            continue
        # Start on an even x and use an 8-pixel multiple width (CI8 texture rows are 8-byte aligned).
        x0, y0, x1, y1 = bbox
        x0 -= x0 % 2
        x1 = min(frame.width, x0 + (x1 - x0 + 7) // 8 * 8)
        crop = frame.crop((x0, y0, x1, y1))
        key = (x0, y0, crop.tobytes())
        if key not in images:
            number = len(images)
            images[key] = number
            image = paletted(crop, background)
            image.save(os.path.join(OUT_IMAGES, f'{number:02d}.png'), transparency=image.info.get('transparency'))
            total_bytes += crop.width * crop.height
        table.append((images[key], x0, y0))

    lines = [
        '// Generated by scripts/make_boot_animation.py from boot_animation/ - do not edit.',
        '',
        '#ifndef BOOT_ANIMATION_FRAMES_H__',
        '#define BOOT_ANIMATION_FRAMES_H__',
        '',
        f'#define BOOT_ANIMATION_FPS          ({FPS})',
        f'#define BOOT_ANIMATION_IMAGES       ({len(images)})',
        f'#define BOOT_ANIMATION_FRAMES       ({len(table)})',
        '',
        '/** @brief Background colour of the animation; the screen is filled with it behind the frames. */',
        f'#define BOOT_ANIMATION_BG_R         (0x{background[0]:02X})',
        f'#define BOOT_ANIMATION_BG_G         (0x{background[1]:02X})',
        f'#define BOOT_ANIMATION_BG_B         (0x{background[2]:02X})',
        '',
        '/** @brief Per frame: image to draw (-1 = background only) and its top-left position. */',
        'static const struct { int8_t image; int16_t x; int16_t y; } boot_animation_frames[BOOT_ANIMATION_FRAMES] = {',
    ]
    lines += [f'    {{ {image}, {x}, {y} }},' for image, x, y in table]
    lines += ['};', '', '#endif', '']
    with open(OUT_HEADER, 'w', newline='\n') as f:
        f.write('\n'.join(lines))

    print(f'{len(table)} frames -> {len(images)} images in {OUT_IMAGES}/ '
          f'({total_bytes / 1024:.0f} KiB as CI8), table in {OUT_HEADER}')


if __name__ == '__main__':
    main()
