#!/usr/bin/env python3
"""Turn the spinning N64 logo GIF into frames for the screenshot placeholder.

The Library shows it in the screenshot area whenever no screenshot is showing (the gallery is
off or the game has none). Reads assets/images/n64logo_anim.gif and writes

  assets/n64logo/NN.png          each frame scaled to HEIGHT px tall (nearest neighbour, so the
                                 logo keeps its flat colours), padded to a 16-pixel multiple
                                 width, transparent background (CI4 sprites)
  src/menu/n64_logo_frames.h     frame count, size, and the playback order and timing

The GIF's frames are evenly timed but not evenly spaced (it mixes single and roughly double
rotation steps, and its last frames barely move), so evenly timed playback speeds up, slows down
and pauses at the loop. Each frame is instead shown for a time proportional to how much the logo
changes before the next one (pixels that differ), so it turns at a steady speed; one turn takes
SPIN_MS. It plays in reverse (REVERSE), so the logo turns the other way.

Usage: scripts/make_n64_logo.py
"""

import glob
import os

from PIL import Image, ImageChops

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..')
GIF = os.path.join(ROOT, 'assets', 'images', 'n64logo_anim.gif')
OUT_IMAGES = os.path.join(ROOT, 'assets', 'n64logo')
OUT_HEADER = os.path.join(ROOT, 'src', 'menu', 'n64_logo_frames.h')

HEIGHT = 168            # GAME_INFO_SCREENSHOT_HEIGHT: the logo fills the screenshot area's height
SPIN_MS = 8000          # one full turn
REVERSE = True          # play the frames last to first


def frames(path):
    """Every frame as RGBA, composited as the GIF's disposal says."""
    gif = Image.open(path)
    canvas = Image.new('RGBA', gif.size, (0, 0, 0, 0))
    for i in range(gif.n_frames):
        gif.seek(i)
        frame = gif.convert('RGBA')
        if gif.disposal_method == 2:
            canvas = Image.new('RGBA', gif.size, (0, 0, 0, 0))
        canvas.alpha_composite(frame)
        yield canvas.copy()


def paletted(image):
    """RGBA with hard alpha to 'P', transparent first."""
    pixels_rgba = list(image.getdata())
    colours = sorted({p[:3] for p in pixels_rgba if p[3] >= 128})
    palette = [(0, 0, 0)] + colours
    index = {c: i + 1 for i, c in enumerate(colours)}
    pixels = bytes(index[p[:3]] if p[3] >= 128 else 0 for p in pixels_rgba)
    out = Image.frombytes('P', image.size, pixels)
    out.putpalette([v for c in palette for v in c])
    return out


def changed_pixels(a, b):
    """How many pixels differ between two frames."""
    return ImageChops.difference(a, b).convert('L').point(lambda v: 255 if v else 0).histogram()[255]


def main():
    os.makedirs(OUT_IMAGES, exist_ok=True)
    for old in glob.glob(os.path.join(OUT_IMAGES, '*.png')):
        os.remove(old)

    images = []
    padded_width = 0
    for frame in frames(GIF):
        width = round(frame.width * HEIGHT / frame.height)
        scaled = frame.resize((width, HEIGHT), Image.Resampling.NEAREST)
        padded_width = (width + 15) // 16 * 16
        canvas = Image.new('RGBA', (padded_width, HEIGHT), (0, 0, 0, 0))
        canvas.paste(scaled, ((padded_width - width) // 2, 0))
        paletted(canvas).save(os.path.join(OUT_IMAGES, f'{len(images):02d}.png'), transparency=0)
        images.append(canvas)
    count = len(images)

    # Playback order, and how long each frame shows: in proportion to the change to the next one.
    order = list(range(count))[::-1] if REVERSE else list(range(count))
    steps = [max(1, changed_pixels(images[order[i]], images[order[(i + 1) % count]])) for i in range(count)]
    total = sum(steps)
    starts, elapsed = [], 0
    for step in steps:
        starts.append(round(elapsed * SPIN_MS / total))
        elapsed += step

    lines = [
        '// Generated by scripts/make_n64_logo.py from assets/images/n64logo_anim.gif - do not edit.',
        '',
        '#ifndef N64_LOGO_FRAMES_H__',
        '#define N64_LOGO_FRAMES_H__',
        '',
        '#include <stdint.h>',
        '',
        f'#define N64_LOGO_FRAMES     ({count})',
        f'#define N64_LOGO_WIDTH      ({padded_width})    // padded; the logo is centred in it',
        f'#define N64_LOGO_HEIGHT     ({HEIGHT})',
        f'#define N64_LOGO_LOOP_MS    ({SPIN_MS})   // one turn',
        '',
        '/** @brief Playback order: the frame to show from start_ms into the turn (timed so it turns steadily). */',
        'static const struct { uint8_t frame; uint16_t start_ms; } n64_logo_sequence[N64_LOGO_FRAMES] = {',
    ]
    lines += [f'    {{ {frame}, {start} }},' for frame, start in zip(order, starts)]
    lines += ['};', '', '#endif', '']
    with open(OUT_HEADER, 'w', newline='\n') as f:
        f.write('\n'.join(lines))

    shortest = min(steps) * SPIN_MS / total
    longest = max(steps) * SPIN_MS / total
    print(f'{count} frames, {padded_width}x{HEIGHT}, one turn in {SPIN_MS / 1000:g}s; '
          f'frames show for {shortest:.0f}-{longest:.0f}ms')


if __name__ == '__main__':
    main()
