#!/usr/bin/env python3
"""Turn the spinning N64 logo GIF into frames for the screenshot placeholder.

The Library shows it in the screenshot area whenever no screenshot is showing (the gallery is
off, the game has none, or its first one is still loading). Reads assets/images/n64logo_anim.gif
and writes

  assets/n64logo/NN.png          each frame scaled to HEIGHT px tall (nearest neighbour, so the
                                 logo keeps its flat colours), padded to a 16-pixel multiple
                                 width, transparent background (CI4 sprites)
  src/menu/n64_logo_frames.h     frame count, size and timing

Usage: scripts/make_n64_logo.py
"""

import glob
import os

from PIL import Image

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..')
GIF = os.path.join(ROOT, 'assets', 'images', 'n64logo_anim.gif')
OUT_IMAGES = os.path.join(ROOT, 'assets', 'n64logo')
OUT_HEADER = os.path.join(ROOT, 'src', 'menu', 'n64_logo_frames.h')

HEIGHT = 168            # GAME_INFO_SCREENSHOT_HEIGHT: the logo fills the screenshot area's height
SPIN_MS = 6000          # one full turn


def frames(path):
    """Every frame as RGBA, composited as the GIF's disposal says."""
    gif = Image.open(path)
    canvas = Image.new('RGBA', gif.size, (0, 0, 0, 0))
    for i in range(gif.n_frames):
        gif.seek(i)
        frame = gif.convert('RGBA')
        if gif.disposal_method == 2:
            canvas = Image.new('RGBA', gif.size, (0, 0, 0, 0))
        canvas.alpha_composite(frame)
        yield canvas.copy()


def paletted(image):
    """RGBA with hard alpha to 'P', transparent first."""
    colours = sorted({p[:3] for p in image.getdata() if p[3] >= 128})
    palette = [(0, 0, 0)] + colours
    index = {c: i + 1 for i, c in enumerate(colours)}
    pixels = bytes(index[p[:3]] if p[3] >= 128 else 0 for p in image.getdata())
    out = Image.frombytes('P', image.size, pixels)
    out.putpalette([v for c in palette for v in c])
    return out


def main():
    os.makedirs(OUT_IMAGES, exist_ok=True)
    for old in glob.glob(os.path.join(OUT_IMAGES, '*.png')):
        os.remove(old)

    count = 0
    for count, frame in enumerate(frames(GIF), start=1):
        width = round(frame.width * HEIGHT / frame.height)
        scaled = frame.resize((width, HEIGHT), Image.Resampling.NEAREST)
        padded_width = (width + 15) // 16 * 16
        canvas = Image.new('RGBA', (padded_width, HEIGHT), (0, 0, 0, 0))
        canvas.paste(scaled, ((padded_width - width) // 2, 0))
        paletted(canvas).save(os.path.join(OUT_IMAGES, f'{count - 1:02d}.png'), transparency=0)

    lines = [
        '// Generated by scripts/make_n64_logo.py from assets/images/n64logo_anim.gif - do not edit.',
        '',
        '#ifndef N64_LOGO_FRAMES_H__',
        '#define N64_LOGO_FRAMES_H__',
        '',
        f'#define N64_LOGO_FRAMES     ({count})',
        f'#define N64_LOGO_WIDTH      ({padded_width})    // padded; the logo is centred in it',
        f'#define N64_LOGO_HEIGHT     ({HEIGHT})',
        f'#define N64_LOGO_FRAME_MS   ({round(SPIN_MS / count)})     // one turn in {SPIN_MS / 1000:g}s',
        '',
        '#endif',
        '',
    ]
    with open(OUT_HEADER, 'w', newline='\n') as f:
        f.write('\n'.join(lines))
    print(f'{count} frames, {padded_width}x{HEIGHT}, to {OUT_IMAGES}')


if __name__ == '__main__':
    main()
